from typing import Protocol, Optional, Any, Tuple
from src.domain_objects import ImageSettings


class IRepository(Protocol):
    """
    Interface for settings and metadata persistence.
    """

    def save_file_settings(self, file_hash: str, settings: ImageSettings) -> None: ...
    def load_file_settings(self, file_hash: str) -> Optional[ImageSettings]: ...
    def save_global_setting(self, key: str, value: Any) -> None: ...
    def get_global_setting(self, key: str, default: Any = None) -> Any: ...
    def initialize(self) -> None: ...


class IAssetStore(Protocol):
    """
    Interface for physical asset management.
    Handles zero-copy registration for local files and persistent thumbnail caching.
    """

    def register_asset(
        self, source: Any, session_id: str
    ) -> Optional[Tuple[str, str]]: ...

    def get_thumbnail(self, file_hash: str) -> Optional[Any]: ...
    def save_thumbnail(self, file_hash: str, image: Any) -> None: ...

    def remove(self, file_path: str) -> None: ...
    def clear_session_assets(self, session_id: str) -> None: ...
    def initialize(self) -> None: ...
    def clear_all(self) -> None: ...
