"""Source tokens: two configs share a token only if they decode to the same pixels.

A token keys every cache holding an assembled source. A field missing from one is
invisible until a stale buffer is served for the setting the user just changed — which
is how an HDR render-exposure control once moved a value with no effect on the picture.
So the test is parametric over the dataclass rather than over a list of field names: a
field added later is covered without anyone remembering to come back here.
"""

import os
import unittest
from dataclasses import fields, replace

from negpy.domain.models import WorkspaceConfig
from negpy.features.hdr.models import HdrConfig, hdr_token
from negpy.features.rgbscan.logic import rgbscan_token
from negpy.features.rgbscan.models import RgbScanConfig
from negpy.features.stitch.models import StitchConfig, stitch_token
from negpy.services.rendering.source_identity import source_token


def _vary(value):
    """A different value of the same type, so `replace` keeps the config well-formed."""
    if isinstance(value, bool):
        return not value
    if isinstance(value, str):
        return value + "x"
    if isinstance(value, tuple):
        return value[:-1] if value else ((0.5,),)
    if isinstance(value, (int, float)):
        return value + 1
    raise AssertionError(f"no variation defined for {type(value)!r} — extend _vary")


class TokenCoverage(unittest.TestCase):
    def _assert_every_field_matters(self, config, token_fn, skip=()):
        base = token_fn(config)
        self.assertNotEqual(base, "", "fixture must be active, or every token is empty")
        for field in fields(config):
            if field.name in skip:
                continue
            varied = replace(config, **{field.name: _vary(getattr(config, field.name))})
            other = token_fn(varied)
            self.assertNotEqual(base, other, f"{type(config).__name__}.{field.name} is missing from its token")

    def test_every_hdr_field_changes_the_token(self):
        cfg = HdrConfig(
            hdr_enabled=True,
            hdr_paths=(__file__,),
            hdr_ratios=(1.0, 2.0),
            hdr_align=True,
            hdr_anchor=__file__,
        )
        # hdr_enabled off is inactive, which is "" by contract rather than a different digest.
        self._assert_every_field_matters(cfg, hdr_token, skip=("hdr_enabled",))
        self.assertEqual(hdr_token(replace(cfg, hdr_enabled=False)), "")

    def test_every_rgbscan_field_changes_the_token(self):
        cfg = RgbScanConfig(enabled=True, green_path=__file__, blue_path=__file__, align=True)
        self._assert_every_field_matters(cfg, rgbscan_token, skip=("enabled", "green_path", "blue_path"))
        # Paths are in the token by identity *and* mtime; varying them makes them unreadable.
        self.assertEqual(rgbscan_token(replace(cfg, green_path="/gone.dng")), "")
        self.assertEqual(rgbscan_token(replace(cfg, enabled=False)), "")

    def test_every_stitch_field_changes_the_token(self):
        cfg = StitchConfig(
            stitch_enabled=True,
            stitch_paths=(__file__,),
            stitch_transforms=((1.0, 0.0, 0.0, 0.0, 1.0, 0.0),),
            stitch_canvas=(100, 200),
            stitch_sizes=((50, 60),),
            stitch_triplets=((__file__, __file__),),
            stitch_align=True,
        )
        self._assert_every_field_matters(cfg, stitch_token, skip=("stitch_enabled", "stitch_paths"))
        self.assertEqual(stitch_token(replace(cfg, stitch_enabled=False)), "")

    def test_an_unreachable_source_is_not_assemblable(self):
        """ "" is the contract for "cannot be assembled" — callers fall back to the plain
        frame rather than raising from inside a decode."""
        self.assertEqual(hdr_token(HdrConfig(hdr_enabled=True, hdr_paths=("/nowhere.nef",))), "")

    def test_a_rewrite_within_the_same_second_still_invalidates(self):
        """Whole-second mtimes miss a companion exposure regenerated by a script moments
        after the last decode; size and nanosecond mtime do not."""
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "green.dng")
            with open(path, "wb") as f:
                f.write(b"old")
            cfg = RgbScanConfig(enabled=True, green_path=path, blue_path=path, align=True)
            before = rgbscan_token(cfg)
            with open(path, "wb") as f:
                f.write(b"new-content-different-size")
            self.assertNotEqual(before, rgbscan_token(cfg))


class DispatchOnTheToken(unittest.TestCase):
    """apply_config is the one place that knows a source change needs a re-decode.

    Before it existed, each control decided for itself, and the ones that got it wrong
    were silent: the value was stored and honoured on export, and the canvas never moved.
    """

    def _controller(self, config):
        from unittest.mock import MagicMock

        controller = MagicMock()
        controller.state.config = config
        controller.state.current_file_path = "/frames/a.nef"
        return controller

    def _apply(self, controller, new_config):
        from negpy.desktop.controller import AppController

        AppController.apply_config(controller, new_config)

    def test_a_source_change_re_decodes(self):
        base = WorkspaceConfig()
        controller = self._controller(base)
        merged = replace(base, hdr=HdrConfig(hdr_enabled=True, hdr_paths=(__file__,), hdr_ratios=(1.0, 2.0)))

        self._apply(controller, merged)

        controller.load_file.assert_called_once()
        controller.request_render.assert_not_called()
        # The bounds analysis would otherwise run against the stale pre-reload buffer.
        self.assertFalse(controller.session.update_config.call_args.kwargs["render"])

    def test_an_edit_only_re_renders(self):
        base = WorkspaceConfig()
        controller = self._controller(base)

        self._apply(controller, replace(base, exposure=replace(base.exposure, density=1.4)))

        controller.request_render.assert_called_once()
        controller.load_file.assert_not_called()


class SourceToken(unittest.TestCase):
    def test_covers_each_assembly_and_the_decode_itself(self):
        base = WorkspaceConfig()
        plain = source_token(base)
        # linear_raw switches use_camera_wb, so it changes the decoded numbers.
        self.assertNotEqual(plain, source_token(replace(base, process=replace(base.process, linear_raw=not base.process.linear_raw))))
        merged = replace(base, hdr=HdrConfig(hdr_enabled=True, hdr_paths=(__file__,), hdr_ratios=(1.0, 2.0)))
        self.assertNotEqual(plain, source_token(merged))

    def test_a_render_only_setting_does_not_force_a_decode(self):
        """The token decides re-decode vs re-render, so a stage's control must not appear
        in it — flat-field is applied as a stage everywhere except inside a stitch."""
        base = WorkspaceConfig()
        ff = replace(base, flatfield=replace(base.flatfield, apply=True, profile_id="p1"))
        self.assertEqual(source_token(base), source_token(ff))
        self.assertEqual(source_token(base), source_token(replace(base, exposure=replace(base.exposure, density=1.7))))
