from src.domain_objects import AppConfig, ProcessingParams

# --- APP CONFIGURATION ---
# Global application constants
APP_CONFIG: AppConfig = {
    "preview_max_res": 1500,
    "display_width": 1500,
    "thumbnail_size": 120,
    "max_workers": 8,
    "edits_db_path": "user/edits.db",
    "settings_db_path": "user/settings.db",
    "presets_dir": "user/presets",
    "cache_dir": "user/cache",
    "default_export_dir": "export",
    "autocrop_detect_res": 1500,
    "adobe_rgb_profile": "icc/AdobeCompat-v4.icc",
}

# --- DEFAULT SETTINGS ---
# The baseline parameters for every newly imported RAW file
DEFAULT_SETTINGS: ProcessingParams = {
    "density": 1.0,
    "grade": 2.5,
    "toe": 0.0,
    "shoulder": 0.0,
    "auto_wb": False,
    "shadow_desat_strength": 1.0,
    "exposure": 0.0,
    "dust_remove": True,
    "dust_threshold": 0.55,
    "dust_size": 2,
    "c_noise_remove": True,
    "c_noise_strength": 25,
    "sharpen": 0.20,
    "rotation": 0,
    "fine_rotation": 0.0,
    "wb_cyan": 0,
    "wb_magenta": 0,
    "wb_yellow": 0,
    "temperature": 0.0,
    "shadow_temp": 0.0,
    "highlight_temp": 0.0,
    "color_separation": 1.0,
    "saturation": 1.0,
    "autocrop": True,
    "autocrop_offset": 5,
    "autocrop_ratio": "3:2",
    "export_color_space": "sRGB",
    "export_fmt": "JPEG",
    "export_size": 27.0,
    "export_dpi": 300,
    "export_add_border": True,
    "export_border_size": 0.25,
    "export_border_color": "#ffffff",
    "export_path": APP_CONFIG["default_export_dir"],
    "process_mode": "C41",
    "manual_dust_spots": [],
    "manual_dust_size": 4,
    "local_adjustments": [],
    "active_adjustment_idx": -1,
}
